apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-persistent-volume-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce # can also be: ReadOnlyMany || ReadWriteMany
  resources:
    requests:
      storage: 2Gi
